#!/bin/sh

set -e

[ -f /etc/default/openhab2 ] && . /etc/default/openhab2

RESTART_FLAG_FILE=/var/lib/openhab2/.restartOnUpgrade

stopOpenHAB() {
	if [ -x /bin/systemctl ] ; then
		/bin/systemctl --no-reload stop openhab2.service > /dev/null 2>&1 || true
	elif [ -x "/etc/init.d/openhab2" ]; then
		if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
			invoke-rc.d openhab2 stop > /dev/null 2>&1 || true
		else
			/etc/init.d/openhab2 stop > /dev/null 2>&1 || true
		fi
		# waiting for the openhab2 process stop (max 10 seconds), otherwise the removal of the user will fail.
		# workaround /etc/init.d/openhab2 stop the service needs some time to stop
		sleep 5
	fi
}

flagRestart() {
	startOpenHAB() {
	if [ -x /bin/systemctl ] ; then
		if /bin/systemctl status openhab2.service > /dev/null 2>&1; then
			touch ${RESTART_FLAG_FILE}
		fi
	elif [ -x "/etc/init.d/openhab2" ]; then
		if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
			if invoke-rc.d openhab2 status > /dev/null 2>&1; then
				touch ${RESTART_FLAG_FILE}
			fi
		else
			if /etc/init.d/openhab2 status > /dev/null 2>&1; then
				touch ${RESTART_FLAG_FILE}
			fi
		fi
	fi
	return 0
}

case "$1" in
	upgrade)
		flagRestart
		stopOpenHAB
        exit 0
		;;
	remove|deconfigure)
		stopOpenHAB
		exit 0
		;;
	failed-upgrade)
		;;
esac

exit 0
