#!/bin/sh

echo "Please use your system's package manager to update!"
echo "    e.g. \"sudo apt-get update && sudo apt-get upgrade\""
echo "         \"sudo yum update\""
echo ""
echo "See https://docs.openhab.org/installation/linux.html for information."
