#!/bin/sh
#
# On .deb based systems:
# Executed on old package before all other scripts
#   $1=upgrade              : On upgrade
#   $2=remove               : On any uninstall
#
# On .rpm based systems:
# Executed on old package (after the installation of the new package on upgrade...)
#   $1=0                    : On removal
#   $1=1                    : On upgrade

set -e

[ -f /etc/default/openhab ] && . /etc/default/openhab

RESTART_FLAG_FILE=/var/lib/openhab/.restartOnUpgrade

stopOpenHAB() {
  if [ -x /bin/systemctl ] ; then
    /bin/systemctl --no-reload stop openhab.service > /dev/null 2>&1 || true
  elif [ -x "/etc/init.d/openhab" ]; then
    if [ -x "$(which invoke-rc.d 2>/dev/null)" ]; then
      invoke-rc.d openhab stop > /dev/null 2>&1 || true
    else
      /etc/init.d/openhab stop > /dev/null 2>&1 || true
    fi
    # Waiting for the openHAB process to stop, otherwise the removal of the user will fail.
    # workaround for /etc/init.d/openhab: The service needs some time to stop
    sleep 5
  fi
}

flagRestart() {
  if [ -x /bin/systemctl ] ; then
    if /bin/systemctl status openhab.service > /dev/null 2>&1; then
      touch ${RESTART_FLAG_FILE}
    fi
  elif [ -x "/etc/init.d/openhab" ]; then
    if [ -x "$(which invoke-rc.d 2>/dev/null)" ]; then
      if invoke-rc.d openhab status > /dev/null 2>&1; then
        touch ${RESTART_FLAG_FILE}
      fi
    else
      if /etc/init.d/openhab status > /dev/null 2>&1; then
        touch ${RESTART_FLAG_FILE}
      fi
    fi
  fi
  return 0
}

case "$1" in
  upgrade)
    flagRestart
    stopOpenHAB
    exit 0
    ;;
  remove|deconfigure|0)
    # 0 Indicates removal on an RPM system
    stopOpenHAB
    exit 0
    ;;
  failed-upgrade)
    ;;
esac

exit 0
